name: Connect_to_s4

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: connect to s3
        run: |
          aws s3 cp .github/workflows/check.txt s3://github-s3-pratice/test1/

        env:
          AWS_ACCESS_KEY_ID: $ {{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: $ {{secrets.AWS_REGION}}
          AWS_SESSION_TOKEN: $ {{ secrets.AWS_SESSION_TOKEN }}
