name: Connect_s3

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: connect_s3
        run: |
          aws s3 cp .github/workflows/a.txt s3://github-s3-pratice/test1/
          aws configure set region $AWS_REGION

        env:
          AWS_ACCESS_KEY_ID: ASIAQGNE3WZCXMG3GSHI
          AWS_SECRET_ACCESS_KEY: $ {{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: $ {{secrets.AWS_SESSION_TOKEN}}
